import { Profile, Room, Message } from "@/types/chat";

export const CURRENT_USER_ID = "user-1";

export const profiles: Profile[] = [
  { id: "user-1", full_name: "You", avatar_url: null, role: "student" },
  { id: "user-2", full_name: "Prof. Adams", avatar_url: null, role: "teacher" },
  { id: "user-3", full_name: "Sarah Chen", avatar_url: null, role: "student" },
  { id: "user-4", full_name: "Mike Ross", avatar_url: null, role: "student" },
];

export const rooms: Room[] = [
  {
    id: "room-1",
    name: "CS 301 — Data Structures",
    type: "group",
    created_by: "user-2",
    last_message: "Don't forget the assignment is due Friday!",
    last_message_at: "2026-02-10T14:30:00Z",
  },
  {
    id: "room-2",
    name: "Prof. Adams",
    type: "direct",
    created_by: "user-2",
    last_message: "Can you review my submission?",
    last_message_at: "2026-02-10T13:15:00Z",
  },
  {
    id: "room-3",
    name: "Announcements",
    type: "announcement",
    created_by: "user-2",
    last_message: "Midterm grades are posted.",
    last_message_at: "2026-02-09T09:00:00Z",
  },
  {
    id: "room-4",
    name: "Study Group — Algo",
    type: "group",
    created_by: "user-3",
    last_message: "Anyone free to meet at 5?",
    last_message_at: "2026-02-10T11:45:00Z",
  },
];

export const messagesByRoom: Record<string, Message[]> = {
  "room-1": [
    {
      id: "msg-1",
      room_id: "room-1",
      sender_id: "user-2",
      sender_name: "Prof. Adams",
      content: "Welcome to CS 301. Please introduce yourselves!",
      message_type: "text",
      metadata: {},
      created_at: "2026-02-08T09:00:00Z",
    },
    {
      id: "msg-2",
      room_id: "room-1",
      sender_id: "user-3",
      sender_name: "Sarah Chen",
      content: "Hi everyone! I'm Sarah, junior CS major.",
      message_type: "text",
      metadata: {},
      created_at: "2026-02-08T09:05:00Z",
    },
    {
      id: "msg-3",
      room_id: "room-1",
      sender_id: "user-1",
      sender_name: "You",
      content: "Hey! Excited for this class.",
      message_type: "text",
      metadata: {},
      created_at: "2026-02-08T09:10:00Z",
    },
    {
      id: "msg-4",
      room_id: "room-1",
      sender_id: "user-2",
      sender_name: "Prof. Adams",
      content: "Assignment 1: Implement a Binary Search Tree",
      message_type: "assignment",
      metadata: { due_date: "2026-02-14T23:59:00Z", max_score: 100 },
      created_at: "2026-02-09T10:00:00Z",
    },
    {
      id: "msg-5",
      room_id: "room-1",
      sender_id: "user-1",
      sender_name: "You",
      content: "Submitted my BST implementation.",
      message_type: "submission",
      metadata: { file_url: "https://storage.example.com/bst.zip" },
      created_at: "2026-02-10T08:00:00Z",
    },
    {
      id: "msg-6",
      room_id: "room-1",
      sender_id: "user-4",
      sender_name: "Mike Ross",
      content: "Is the BST supposed to be self-balancing?",
      message_type: "text",
      metadata: {},
      created_at: "2026-02-10T12:00:00Z",
    },
    {
      id: "msg-7",
      room_id: "room-1",
      sender_id: "user-2",
      sender_name: "Prof. Adams",
      content: "No, a basic BST is fine for this one.",
      message_type: "text",
      metadata: {},
      created_at: "2026-02-10T12:30:00Z",
    },
    {
      id: "msg-8",
      room_id: "room-1",
      sender_id: "user-2",
      sender_name: "Prof. Adams",
      content: "Don't forget the assignment is due Friday!",
      message_type: "text",
      metadata: {},
      created_at: "2026-02-10T14:30:00Z",
    },
  ],
  "room-2": [
    {
      id: "msg-20",
      room_id: "room-2",
      sender_id: "user-2",
      sender_name: "Prof. Adams",
      content: "Feel free to reach out if you need help.",
      message_type: "text",
      metadata: {},
      created_at: "2026-02-09T10:00:00Z",
    },
    {
      id: "msg-21",
      room_id: "room-2",
      sender_id: "user-1",
      sender_name: "You",
      content: "Can you review my submission?",
      message_type: "text",
      metadata: {},
      created_at: "2026-02-10T13:15:00Z",
    },
  ],
  "room-3": [
    {
      id: "msg-30",
      room_id: "room-3",
      sender_id: "user-2",
      sender_name: "Prof. Adams",
      content: "Campus will be closed Monday for maintenance.",
      message_type: "text",
      metadata: {},
      created_at: "2026-02-07T09:00:00Z",
    },
    {
      id: "msg-31",
      room_id: "room-3",
      sender_id: "user-2",
      sender_name: "Prof. Adams",
      content: "Midterm grades are posted.",
      message_type: "text",
      metadata: {},
      created_at: "2026-02-09T09:00:00Z",
    },
  ],
  "room-4": [
    {
      id: "msg-40",
      room_id: "room-4",
      sender_id: "user-3",
      sender_name: "Sarah Chen",
      content: "We should review chapter 5 before the quiz.",
      message_type: "text",
      metadata: {},
      created_at: "2026-02-10T10:00:00Z",
    },
    {
      id: "msg-41",
      room_id: "room-4",
      sender_id: "user-1",
      sender_name: "You",
      content: "Good idea. I'll bring my notes.",
      message_type: "text",
      metadata: {},
      created_at: "2026-02-10T10:30:00Z",
    },
    {
      id: "msg-42",
      room_id: "room-4",
      sender_id: "user-4",
      sender_name: "Mike Ross",
      content: "Anyone free to meet at 5?",
      message_type: "text",
      metadata: {},
      created_at: "2026-02-10T11:45:00Z",
    },
  ],
};
